import type {CommandId} from '../commands/types'
import type {IconName} from './icons'

export const IconMap: Record<CommandId, IconName> = {
    'text:bold': 'lucide:bold',
    'text:italic': 'lucide:italic',
    'text:underline': 'lucide:underline',
    'text:align-left': 'lucide:text-left',
    'text:align-center': 'lucide:text-center',
    'text:align-right': 'lucide:text-right',
    'align:left': 'lucide:align-left',
    'align:center': 'lucide:align-center-horizontal',
    'align:right': 'lucide:align-right',
    'align:top': 'lucide:align-top',
    'align:middle': 'lucide:align-middle',
    'align:bottom': 'lucide:align-bottom',
    'distribute:horizontal': 'lucide:distribute-horizontal',
    'distribute:vertical': 'lucide:distribute-vertical',
    'distribute:space-horizontal': 'lucide:space-horizontal',
    'distribute:space-vertical': 'lucide:space-vertical',
    'resize:match-width-min': 'lucide:match-width-min',
    'resize:match-width-max': 'lucide:match-width-max',
    'resize:match-height-min': 'lucide:match-height-min',
    'resize:match-height-max': 'lucide:match-height-max',
    'resize:match-both-min': 'lucide:match-both-min',
    'resize:match-both-max': 'lucide:match-both-max',
    'grouping:group': 'lucide:group',
    'grouping:ungroup': 'lucide:ungroup',
    'grouping:lock': 'lucide:lock',
    'grouping:unlock': 'lucide:unlock',
    'grid:toggle': 'lucide:grid',
    'grid:snap': 'lucide:snap',
    'grid:guides': 'lucide:guides',
    'zoom:in': 'lucide:zoom-in',
    'zoom:out': 'lucide:zoom-out',
    'zoom:reset': 'lucide:zoom-reset',
    'zoom:actual': 'lucide:zoom-actual',
    'zoom:fit': 'lucide:zoom-fit',
}
